services:
  mqtt-bridge:
    build: .
    container_name: ttn-bridge
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - ../.env
    ports:
      - "5001:5001"
    volumes:
      - ./certs:/app/certs